### ISSUE TITLE
fix_side_chain with modeller fails on log file output

### ISSUE THREAD

**Issue by GregorySchwing** [bioexcel/biobb_model#21]
**Describe the bug**
Logging method signature appears to have been changed.
from biobb_common.tools import file_utils as fu
def log(string: str, local_log: logging.Logger = None, global_log: logging.Logger = None):

/lib/python3.9/site-packages/biobb_model/model/common.py", line 11, in modeller_installed
    fu.log(f"Modeller automodel class: {automodel.automodel}", out_log=out_log)
TypeError: log() got an unexpected keyword argument 'out_log'

Traceback (most recent call last):
  File "/home/greg/Desktop/SolvationDataset/workflow/.snakemake/scripts/tmpml2wpjqo.fixProteinStructure.py", line 16, in <module>
    fix_side_chain(input_pdb_path=snakemake.input.PDB, 
  File "/home/greg/Desktop/SolvationDataset/workflow/.snakemake/conda/51ae00ff88b51409e09cb734a82fb85e_/lib/python3.9/site-packages/biobb_model/model/fix_side_chain.py", line 111, in fix_side_chain
    return FixSideChain(input_pdb_path=input_pdb_path,
  File "/home/greg/Desktop/SolvationDataset/workflow/.snakemake/conda/51ae00ff88b51409e09cb734a82fb85e_/lib/python3.9/site-packages/biobb_common/tools/file_utils.py", line 322, in wrapper_log
    value = func(*args, **kwargs)
  File "/home/greg/Desktop/SolvationDataset/workflow/.snakemake/conda/51ae00ff88b51409e09cb734a82fb85e_/lib/python3.9/site-packages/biobb_model/model/fix_side_chain.py", line 89, in launch
    if modeller_installed(self.out_log, self.global_log):
  File "/home/greg/Desktop/SolvationDataset/workflow/.snakemake/conda/51ae00ff88b51409e09cb734a82fb85e_/lib/python3.9/site-packages/biobb_model/model/common.py", line 11, in modeller_installed
    fu.log(f"Modeller automodel class: {automodel.automodel}", out_log=out_log)
TypeError: log() got an unexpected keyword argument 'out_log'

**To Reproduce**

Installed biobb_model via mamba.  Also installed modeller via mamba

YML file
```
name: biobb_model
channels:
  - bioconda
  - salilab
dependencies:
  - biobb_model
  - modeller
variables:
  KEY_MODELLER: 'MODELIRANJE'
```

Ran this code

```
# Downloading desired PDB file 
# Import module
from pathlib import Path
# Check & Fix PDB
# Import module
from biobb_model.model.fix_side_chain import fix_side_chain
prop = { 'use_modeller': True,
         'modeller_key': 'MODELIRANJE'
        }

# Create and launch bb
fix_side_chain(input_pdb_path=snakemake.input.PDB, 
             output_pdb_path=snakemake.output.PDB,
             properties=prop)

```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu]
 - Python version: [e.g. 3.8]
 - BioBB version [e.g. 4.0.0]

**Additional context**

**Comment by ThaNikkitz** [comment]
It's by no means a clean fix, but a workaround:
You can edit the input of `fu.log` in the file `biobb_model/model/common.py` file, in your case
`/home/greg/Desktop/SolvationDataset/workflow/.snakemake/conda/51ae00ff88b51409e09cb734a82fb85e_/lib/python3.9/site-packages/biobb_model/model/common.py`

Change the input of `fu.log` to
`fu.log(f"Modeller automodel class: {automodel.automodel}", **local_log=out_log**)`

Again, it's a quick workaround, not a real fix.
